name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: "npm"

      - name: Clean install dependencies
        run: |
          rm -rf node_modules package-lock.json
          npm install

      - name: Verify installation
        run: |
          echo "Node version: $(node --version)"
          echo "NPM version: $(npm --version)"
          echo "Checking node_modules/.bin/:"
          ls -la node_modules/.bin/ || echo "No .bin directory found"
          echo "Checking for vite:"
          which vite || echo "Vite not found in PATH"
          echo "Checking local vite:"
          ls -la node_modules/.bin/vite || echo "Local vite not found"
          echo "Package.json scripts:"
          cat package.json | grep -A 10 '"scripts"'

      - name: Build project
        run: npm run build
        env:
          VITE_POKEMON_TCG_API_KEY: ${{ secrets.POKEMON_TCG_API_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./docs"

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
